# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixsqp_rcpp <- function(L, w, x0, tol, zerothreshold, zerosearchdir, suffdecr, stepsizereduce, minstepsize, e, numiter, maxiteractiveset, verbose) {
    .Call('_fastTopics_mixsqp_rcpp', PACKAGE = 'fastTopics', L, w, x0, tol, zerothreshold, zerosearchdir, suffdecr, stepsizereduce, minstepsize, e, numiter, maxiteractiveset, verbose)
}

