# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altsqp_update_factors_rcpp <- function(X, F, L, xscol, ls, e, control) {
    .Call('_fastTopics_altsqp_update_factors_rcpp', PACKAGE = 'fastTopics', X, F, L, xscol, ls, e, control)
}

altsqp_update_loadings_rcpp <- function(X, F, L, xsrow, fs, e, control) {
    .Call('_fastTopics_altsqp_update_loadings_rcpp', PACKAGE = 'fastTopics', X, F, L, xsrow, fs, e, control)
}

cost_rcpp <- function(X, A, B, e) {
    .Call('_fastTopics_cost_rcpp', PACKAGE = 'fastTopics', X, A, B, e)
}

mixsqp_rcpp <- function(L, w, x0, e, numiter, control, verbose) {
    .Call('_fastTopics_mixsqp_rcpp', PACKAGE = 'fastTopics', L, w, x0, e, numiter, control, verbose)
}

